NetCleanArchitecture/Gav.RazorPages/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gav.RazorPages.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

NetCleanArchitecture/Gav.RazorPages/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gav.RazorPages.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        [TempData]
        public string Nombre { get; set; }

        public void OnGet(int id, int pg)
        {
            Message = "Your contact page. Id: " + id.ToString() + $" Pagina: {pg}";
        }
    }
}

NetCleanArchitecture/Gav.RazorPages/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gav.RazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NetCleanArchitecture/Gav.RazorPages/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gav.RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public Persona Persona { get; set; }

        [BindProperty]
        public Ciudad Ciudad { get; set; }

        [TempData]
        public string Nombre { get; set; }


        public void OnGet()
        {
            
        }

        public IActionResult OnPost(string param1)
        {
            Nombre = param1;
            return RedirectToPage("Contact");
        }

        public void OnPostPersona()
        {

        }

        public void OnPostPersonaCiudad()
        {

        }
    }

    public class Persona
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }

    public class Ciudad
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Pais { get; set; }
    }
}

NetCleanArchitecture/Gav.RazorPages/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Gav.RazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NetCleanArchitecture/Gav.RazorPages/Pages/Contact.cshtml
@page "{id:int?}/{pg:int?}"
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<h1>@Model.Nombre</h1>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NetCleanArchitecture/Gav.RazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form method="post">
    <h1>Formulario Simple</h1>
    <input type="text" name="param1" placeholder="param1"/>
    <input type="submit" value="Enviar"/>
</form>

<form method="post">
    <h1>Formulario Persona</h1>
    <input asp-for="@Model.Persona.Id" placeholder="Id" />
    <input asp-for="@Model.Persona.Nombre" placeholder="Nombre" />
    <input type="submit" value="Enviar" asp-page-handler="Persona" />
</form>

<form method="post">
    <h1>Formulario Persona y Ciudad</h1>
    <h4>Persona</h4>
    <input asp-for="@Model.Persona.Id" placeholder="Id" />
    <input asp-for="@Model.Persona.Nombre" placeholder="Nombre" />

    <h4>Ciudad</h4>
    <input asp-for="@Model.Ciudad.Id" placeholder="Id" />
    <input asp-for="@Model.Ciudad.Nombre" placeholder="Nombre" />
    <input asp-for="@Model.Ciudad.Pais" placeholder="Pais" />

    <input type="submit" value="Enviar" asp-page-handler="PersonaCiudad" />
</form>